services:   
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 'password'
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  db-migrator:
    build:
      context: ./db
      dockerfile: ../db/Xpense.Utils.Postgres.Migrator/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DOTNET_ENVIRONMENT: Docker

volumes:
  postgres-data: