<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Xpense.Adapters.Postgres</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Commands\" />
    <Folder Include="Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Npgsql" Version="9.0.2" />
  </ItemGroup>



</Project>
